/**
 * Mock dashboard data — monthly AI threat landscape snapshot.
 * Replace with real API calls via src/api/dashboardApi.js when backend is wired.
 *
 * Schema mirrors pipeline output from L5A rawfacts + L5B analytics + L5C external
 * evidence + L6 claims/viewpoints + L7 visualization specs.
 *
 * Every claim/finding/chart includes traceability IDs so drilldown panels can
 * resolve linked evidence, sources, and quotes.
 */

// ── Period ─────────────────────────────────────────────────────────────────────

export const CURRENT_PERIOD  = "2026-05";
export const COMPARE_PERIOD  = "2026-04";

export const MONTHLY_DASHBOARD = {
  period:         CURRENT_PERIOD,
  compare_period: COMPARE_PERIOD,

  // ── Summary ────────────────────────────────────────────────────────────────
  summary: {
    total_sources:      62,
    sources_validated:  51,
    coverage_months:    6,
    categories_assessed:3,
    categories_not_assessed: 1,
    executive_headline: "Prompt injection crossed from research to confirmed operational exploitation. Agentic AI tool-call injection reached consistent PoC stage across independent research groups.",
    confidence:         "medium",
    caveat:             "AI-enabled threats category is not assessed this period due to insufficient evidence.",
    period_label:       "May 2026",
    date_range:         { start: "2026-05-01", end: "2026-05-31" },
  },

  // ── Categories ─────────────────────────────────────────────────────────────
  categories: [
    {
      id:              "llm_threats",
      label:           "LLM Threats",
      color:           "#6366f1",
      source_count:    28,
      claim_counts:    { critical: 2, high: 4, medium: 6 },
      headline:        "Prompt injection crossed from research to operational exploitation.",
      confidence:      "high",
      assessment_status: "assessed",
      top_signal:      "Indirect injection via RAG documents bypassed enterprise guardrails in 3 documented incidents.",
      evidence_strength_distribution: { strong: 5, usable: 12, context: 8, archive: 3 },
      claim_ids:       ["cl_llm_001", "cl_llm_002", "cl_llm_003"],
      viewpoint_ids:   ["vp_llm_001", "vp_llm_002"],
      evidence_ids:    ["ev_src1_001", "ev_src2_001", "ev_src5_001"],
      analytics_evidence_ids: ["ae_llm_atk_vec", "ae_llm_maturity"],
    },
    {
      id:              "agentic_ai_threats",
      label:           "Agentic AI Threats",
      color:           "#0ea5e9",
      source_count:    17,
      claim_counts:    { critical: 0, high: 3, medium: 4 },
      headline:        "Tool-call injection shows a recurring pattern across independent research.",
      confidence:      "medium",
      assessment_status: "assessed",
      top_signal:      "MCP server hijacking demonstrated across 4 independent PoCs.",
      evidence_strength_distribution: { strong: 2, usable: 7, context: 5, archive: 3 },
      claim_ids:       ["cl_agt_001", "cl_agt_002"],
      viewpoint_ids:   ["vp_agt_001"],
      evidence_ids:    ["ev_src3_001", "ev_src6_001"],
      analytics_evidence_ids: ["ae_agt_atk_vec"],
    },
    {
      id:              "traditional_ai_threats",
      label:           "Traditional AI Threats",
      color:           "#f59e0b",
      source_count:    12,
      claim_counts:    { critical: 0, high: 2, medium: 3 },
      headline:        "Data poisoning capability expanded in sophistication.",
      confidence:      "medium",
      assessment_status: "assessed",
      top_signal:      "Backdoor attacks against public training datasets increasing in complexity.",
      evidence_strength_distribution: { strong: 1, usable: 5, context: 4, archive: 2 },
      claim_ids:       ["cl_tai_001"],
      viewpoint_ids:   ["vp_tai_001"],
      evidence_ids:    ["ev_src4_001"],
      analytics_evidence_ids: ["ae_tai_maturity"],
    },
    {
      id:              "ai_enabled_threats",
      label:           "AI-Enabled Threats",
      color:           "#ef4444",
      source_count:    5,
      claim_counts:    { critical: 0, high: 0, medium: 1 },
      headline:        "Insufficient evidence this period — category not assessed.",
      confidence:      "low",
      assessment_status: "evidence_insufficient",
      top_signal:      "Coverage gap: no validated incident or threat-intelligence sources this period.",
      evidence_strength_distribution: { strong: 0, usable: 1, context: 3, archive: 1 },
      claim_ids:       [],
      viewpoint_ids:   [],
      evidence_ids:    [],
      analytics_evidence_ids: [],
    },
  ],

  // ── Claims ─────────────────────────────────────────────────────────────────
  claims: [
    {
      claim_id:         "cl_llm_001",
      claim_type:       "adoption_claim",
      claim_priority:   "critical",
      claim_text:       "Indirect prompt injection via RAG document poisoning has moved from theoretical to confirmed operational exploitation in enterprise deployments.",
      category:         "llm_threats",
      confidence:       "high",
      evidence_sufficiency: "sufficient",
      supporting_evidence_ids: ["ev_src1_001", "ev_src2_001"],
      supporting_analytics_ids: ["ae_llm_atk_vec"],
      supporting_external_ids:  ["extev_cisa_001"],
      supporting_viewpoint_ids: ["vp_llm_001"],
      caveat_if_any:    null,
    },
    {
      claim_id:         "cl_llm_002",
      claim_type:       "trend_claim",
      claim_priority:   "critical",
      claim_text:       "Jailbreak complexity is increasing in correlation with expanded model capability — safety mitigations lag capability growth.",
      category:         "llm_threats",
      confidence:       "medium",
      evidence_sufficiency: "sufficient",
      supporting_evidence_ids: ["ev_src2_001", "ev_src7_001"],
      supporting_analytics_ids: ["ae_llm_maturity"],
      supporting_external_ids:  [],
      supporting_viewpoint_ids: ["vp_llm_001"],
      caveat_if_any:    "Trend requires 3+ months confirmed; this is 2 months — label as early signal pending next period.",
    },
    {
      claim_id:         "cl_llm_003",
      claim_type:       "category_insight",
      claim_priority:   "high",
      claim_text:       "CISA identifies prompt injection as the top operational risk for federal LLM deployments in new advisory.",
      category:         "llm_threats",
      confidence:       "high",
      evidence_sufficiency: "sufficient",
      supporting_evidence_ids: ["ev_src5_001"],
      supporting_analytics_ids: [],
      supporting_external_ids:  ["extev_cisa_001"],
      supporting_viewpoint_ids: [],
      caveat_if_any:    "Governance signal — cannot confirm adversary adoption from this source type alone.",
    },
    {
      claim_id:         "cl_agt_001",
      claim_type:       "capability_shift_claim",
      claim_priority:   "high",
      claim_text:       "Tool-call injection via malicious MCP server responses demonstrated across 4 independent research groups.",
      category:         "agentic_ai_threats",
      confidence:       "medium",
      evidence_sufficiency: "sufficient",
      supporting_evidence_ids: ["ev_src3_001", "ev_src6_001"],
      supporting_analytics_ids: ["ae_agt_atk_vec"],
      supporting_external_ids:  [],
      supporting_viewpoint_ids: ["vp_agt_001"],
      caveat_if_any:    "PoC stage only — no confirmed operational exploitation yet.",
    },
    {
      claim_id:         "cl_agt_002",
      claim_type:       "outlook",
      claim_priority:   "high",
      claim_text:       "Autonomous agent permission abuse is likely to emerge as the next agentic AI attack vector within 3-6 months.",
      category:         "agentic_ai_threats",
      confidence:       "low",
      evidence_sufficiency: "partial",
      supporting_evidence_ids: ["ev_src6_001"],
      supporting_analytics_ids: [],
      supporting_external_ids:  [],
      supporting_viewpoint_ids: ["vp_agt_001"],
      caveat_if_any:    "Low confidence — based on 1 research source. Monitor for operational signals.",
    },
    {
      claim_id:         "cl_tai_001",
      claim_type:       "capability_shift_claim",
      claim_priority:   "high",
      claim_text:       "Backdoor injection into open-source model weights on public repositories requires fewer than 0.01% poisoned samples.",
      category:         "traditional_ai_threats",
      confidence:       "medium",
      evidence_sufficiency: "sufficient",
      supporting_evidence_ids: ["ev_src4_001"],
      supporting_analytics_ids: ["ae_tai_maturity"],
      supporting_external_ids:  [],
      supporting_viewpoint_ids: ["vp_tai_001"],
      caveat_if_any:    "Lab-demonstrated only — no confirmed operational deployment of this technique.",
    },
  ],

  // ── Viewpoints ─────────────────────────────────────────────────────────────
  viewpoints: [
    {
      viewpoint_id:   "vp_llm_001",
      category:       "llm_threats",
      viewpoint_type: "pattern_insight",
      statement:      "Enterprise LLM deployments that enable RAG over untrusted document stores are systematically vulnerable to indirect injection. The attack surface is structural, not misconfiguration-based.",
      supporting_claim_ids:   ["cl_llm_001", "cl_llm_003"],
      supporting_evidence_ids:["ev_src1_001", "ev_src2_001", "ev_src5_001"],
      confidence:     "high",
    },
    {
      viewpoint_id:   "vp_llm_002",
      category:       "llm_threats",
      viewpoint_type: "trend_analysis",
      statement:      "Jailbreak techniques are becoming more modular and transferable across model families, suggesting an emerging market for jailbreak-as-a-service.",
      supporting_claim_ids:   ["cl_llm_002"],
      supporting_evidence_ids:["ev_src2_001", "ev_src7_001"],
      confidence:     "medium",
    },
    {
      viewpoint_id:   "vp_agt_001",
      category:       "agentic_ai_threats",
      viewpoint_type: "capability_assessment",
      statement:      "MCP-enabled agentic systems that execute tool calls without sandboxing or permission verification are structurally vulnerable to injection via malicious server responses.",
      supporting_claim_ids:   ["cl_agt_001", "cl_agt_002"],
      supporting_evidence_ids:["ev_src3_001", "ev_src6_001"],
      confidence:     "medium",
    },
    {
      viewpoint_id:   "vp_tai_001",
      category:       "traditional_ai_threats",
      viewpoint_type: "capability_assessment",
      statement:      "Public model weight repositories have insufficient supply-chain security. Backdoor injection requires minimal poisoning rates, making detection practically difficult.",
      supporting_claim_ids:   ["cl_tai_001"],
      supporting_evidence_ids:["ev_src4_001"],
      confidence:     "medium",
    },
  ],

  // ── Happenings ─────────────────────────────────────────────────────────────
  happenings: [
    {
      happening_id:   "hap_001",
      category:       "llm_threats",
      title:          "Enterprise RAG Deployments Hit by Indirect Injection",
      description:    "3 documented incidents confirmed where indirect prompt injection via poisoned RAG documents bypassed enterprise LLM guardrails.",
      date:           "2026-05-12",
      significance:   "critical",
      evidence_ids:   ["ev_src1_001"],
      claim_ids:      ["cl_llm_001"],
      source_ids:     ["src_nist_001"],
    },
    {
      happening_id:   "hap_002",
      category:       "llm_threats",
      title:          "CISA Issues LLM Security Advisory",
      description:    "CISA published advisory citing prompt injection as top risk for federal LLM deployments.",
      date:           "2026-05-20",
      significance:   "high",
      evidence_ids:   ["ev_src5_001"],
      claim_ids:      ["cl_llm_003"],
      source_ids:     ["src_cisa_001"],
    },
    {
      happening_id:   "hap_003",
      category:       "agentic_ai_threats",
      title:          "4 Independent PoCs Demonstrate MCP Server Hijacking",
      description:    "4 independent research groups demonstrated tool-call injection via malicious MCP server responses within the same month.",
      date:           "2026-05-08",
      significance:   "high",
      evidence_ids:   ["ev_src3_001", "ev_src6_001"],
      claim_ids:      ["cl_agt_001"],
      source_ids:     ["src_arxiv_001"],
    },
    {
      happening_id:   "hap_004",
      category:       "traditional_ai_threats",
      title:          "Backdoor Injection Threshold Lowered to 0.01% Poisoning Rate",
      description:    "Researchers at Google DeepMind demonstrated backdoor injection into 3 HuggingFace models requiring less than 0.01% poisoned training samples.",
      date:           "2026-05-03",
      significance:   "high",
      evidence_ids:   ["ev_src4_001"],
      claim_ids:      ["cl_tai_001"],
      source_ids:     ["src_deepmind_001"],
    },
  ],

  // ── Trends and Patterns ────────────────────────────────────────────────────
  trends_or_patterns: [
    {
      pattern_id:     "tr_001",
      category:       "llm_threats",
      key:            "indirect_prompt_injection",
      label:          "Indirect Prompt Injection via RAG",
      pattern_type:   "recurring_pattern",  // not "trend" — 2 months only
      direction:      "increasing",
      current_count:  14,
      compare_count:  9,
      delta:          5,
      confidence:     "medium",
      caveat:         "Pattern requires ≥3 months to qualify as a validated trend. Currently 2 months — label as recurring_pattern.",
      claim_ids:      ["cl_llm_001"],
      evidence_ids:   ["ev_src1_001", "ev_src2_001"],
    },
    {
      pattern_id:     "tr_002",
      category:       "agentic_ai_threats",
      key:            "mcp_tool_injection",
      label:          "MCP Tool-Call Injection",
      pattern_type:   "early_signal",
      direction:      "increasing",
      current_count:  4,
      compare_count:  1,
      delta:          3,
      confidence:     "low",
      caveat:         "Insufficient months for trend validation. Monitor next period.",
      claim_ids:      ["cl_agt_001"],
      evidence_ids:   ["ev_src3_001"],
    },
    {
      pattern_id:     "tr_003",
      category:       "llm_threats",
      key:            "jailbreak_complexity",
      label:          "Jailbreak Complexity Increase",
      pattern_type:   "recurring_pattern",
      direction:      "increasing",
      current_count:  8,
      compare_count:  5,
      delta:          3,
      confidence:     "medium",
      caveat:         null,
      claim_ids:      ["cl_llm_002"],
      evidence_ids:   ["ev_src2_001", "ev_src7_001"],
    },
  ],

  // ── Early Signals ──────────────────────────────────────────────────────────
  early_signals: [
    {
      signal_id:    "sig_001",
      category:     "agentic_ai_threats",
      signal:       "LLM-to-LLM prompt smuggling via multi-agent orchestration layers.",
      implication:  "May enable lateral movement within agentic pipelines over next 3-6 months.",
      confidence:   "low",
      source_count: 2,
      evidence_ids: ["ev_src6_001"],
      claim_ids:    ["cl_agt_002"],
    },
    {
      signal_id:    "sig_002",
      category:     "llm_threats",
      signal:       "Jailbreak-as-a-service marketplaces emerging on underground forums.",
      implication:  "Reduces attacker barrier; democratises capability.",
      confidence:   "medium",
      source_count: 3,
      evidence_ids: ["ev_src7_001"],
      claim_ids:    ["cl_llm_002"],
    },
    {
      signal_id:    "sig_003",
      category:     "traditional_ai_threats",
      signal:       "Supply-chain attacks targeting open-source model weights on HuggingFace.",
      implication:  "Downstream consumers unaware of embedded backdoors.",
      confidence:   "medium",
      source_count: 2,
      evidence_ids: ["ev_src4_001"],
      claim_ids:    ["cl_tai_001"],
    },
  ],

  // ── 6-Month Outlook ────────────────────────────────────────────────────────
  outlook_6_months: [
    {
      outlook_id:     "out_llm",
      category:       "llm_threats",
      statement:      "Indirect prompt injection via RAG is expected to scale to agentic workflows and multi-turn deployments over the next 3-6 months as enterprise adoption grows.",
      observed_basis: "3 confirmed incidents, 12 research-documented cases, CISA advisory.",
      trajectory:     "escalating",
      confidence:     "medium",
      claim_ids:      ["cl_llm_001", "cl_llm_002"],
      evidence_ids:   ["ev_src1_001", "ev_src2_001"],
    },
    {
      outlook_id:     "out_agt",
      category:       "agentic_ai_threats",
      statement:      "Tool-call injection is likely to progress from PoC to limited operational exploitation within 3-6 months as agentic frameworks gain enterprise adoption.",
      observed_basis: "4 independent PoCs, growing research attention.",
      trajectory:     "escalating",
      confidence:     "low",
      claim_ids:      ["cl_agt_001", "cl_agt_002"],
      evidence_ids:   ["ev_src3_001"],
    },
  ],

  // ── Recommendations ────────────────────────────────────────────────────────
  recommendations: [
    {
      rec_id:       "rec_001",
      category:     "llm_threats",
      priority:     "critical",
      recommendation:"Implement document-level trust boundaries in RAG pipelines. Treat retrieved content as untrusted input — apply the same injection-prevention logic as user queries.",
      rationale:    "3 confirmed incidents trace to unconstrained trust in RAG-retrieved documents.",
      claim_ids:    ["cl_llm_001"],
      evidence_ids: ["ev_src1_001"],
    },
    {
      rec_id:       "rec_002",
      category:     "agentic_ai_threats",
      priority:     "high",
      recommendation:"Require explicit user confirmation for high-privilege tool calls in MCP-enabled agentic systems. Sandbox MCP server responses before execution.",
      rationale:    "4 independent PoCs demonstrate tool-call injection is reproducible without sandboxing.",
      claim_ids:    ["cl_agt_001"],
      evidence_ids: ["ev_src3_001"],
    },
    {
      rec_id:       "rec_003",
      category:     "traditional_ai_threats",
      priority:     "high",
      recommendation:"Implement model weight integrity verification before deploying public open-source models. Treat HuggingFace-sourced weights as untrusted without provenance verification.",
      rationale:    "Backdoor injection is demonstrably effective at <0.01% poisoning rate.",
      claim_ids:    ["cl_tai_001"],
      evidence_ids: ["ev_src4_001"],
    },
  ],

  // ── Visualization Specs (from L5B) ─────────────────────────────────────────
  visualization_specs: [
    {
      visualization_id: "vs_category_bar",
      title:            "Source Volume by Category",
      chart_type:       "bar",
      dashboard_use:    "overview",
      slide_use:        "threat_landscape_overview",
      confidence:       "high",
      insufficient_data:false,
      caveat_if_any:    null,
      chart_data: {
        items: [
          { key: "llm_threats",            label: "LLM Threats",        count: 28, source_ids: ["src_nist_001","src_anthropic_001","src_cisa_001"] },
          { key: "agentic_ai_threats",     label: "Agentic AI",         count: 17, source_ids: ["src_arxiv_001"] },
          { key: "traditional_ai_threats", label: "Traditional AI",     count: 12, source_ids: ["src_deepmind_001"] },
          { key: "ai_enabled_threats",     label: "AI-Enabled Threats", count: 5,  source_ids: [] },
        ],
      },
      supports_claim_types: ["frequency_claim", "category_insight"],
      supports_analytics_evidence_ids: ["ae_llm_atk_vec", "ae_agt_atk_vec", "ae_tai_maturity"],
      interactive_drilldown: { click_target_type: "source_list", linked_source_ids: ["src_nist_001","src_arxiv_001","src_deepmind_001"] },
    },
    {
      visualization_id: "vs_monthly_timeline",
      title:            "Monthly Source Activity by Category",
      chart_type:       "stacked_bar",
      dashboard_use:    "overview,landscape",
      slide_use:        "executive_overview",
      confidence:       "medium",
      insufficient_data:false,
      caveat_if_any:    "Coverage represents ingested sources, not real-world event frequency.",
      chart_data: {
        months: ["2026-01","2026-02","2026-03","2026-04","2026-05"],
        stacks: [
          { key: "llm_threats",            label: "LLM Threats",    values: [8,12,15,18,28] },
          { key: "agentic_ai_threats",     label: "Agentic AI",     values: [3,6,8,12,17] },
          { key: "traditional_ai_threats", label: "Traditional AI", values: [5,8,7,10,12] },
          { key: "ai_enabled_threats",     label: "AI-Enabled",     values: [2,3,4,4,5] },
        ],
      },
      supports_claim_types: ["trend_claim", "frequency_claim"],
      supports_analytics_evidence_ids: ["ae_llm_atk_vec"],
      interactive_drilldown: { click_target_type: "source_list", linked_source_ids: [] },
    },
    {
      visualization_id: "vs_attack_vector_freq",
      title:            "Top Attack Vectors (Corpus Frequency)",
      chart_type:       "bar",
      dashboard_use:    "landscape",
      slide_use:        "category_insight",
      confidence:       "medium",
      insufficient_data:false,
      caveat_if_any:    "Frequency within collected corpus only — does not represent real-world prevalence.",
      chart_data: {
        items: [
          { key: "prompt_injection",         label: "Prompt Injection",        count: 19, source_ids: ["src_nist_001","src_anthropic_001"] },
          { key: "rag_poisoning",            label: "RAG Poisoning",           count: 14, source_ids: ["src_nist_001"] },
          { key: "tool_hijacking",           label: "Tool Hijacking",          count: 8,  source_ids: ["src_arxiv_001"] },
          { key: "mcp_abuse",                label: "MCP Abuse",               count: 6,  source_ids: ["src_arxiv_001"] },
          { key: "model_poisoning",          label: "Model Poisoning",         count: 5,  source_ids: ["src_deepmind_001"] },
          { key: "jailbreak",                label: "Jailbreak",               count: 9,  source_ids: ["src_anthropic_001"] },
          { key: "model_backdoor",           label: "Model Backdoor",          count: 4,  source_ids: ["src_deepmind_001"] },
        ],
      },
      supports_claim_types: ["frequency_claim", "category_insight"],
      supports_analytics_evidence_ids: ["ae_llm_atk_vec", "ae_agt_atk_vec"],
      interactive_drilldown: { click_target_type: "mixed", drilldown_keys: ["prompt_injection","rag_poisoning"] },
    },
    {
      visualization_id: "vs_maturity_funnel",
      title:            "Operational Maturity Pipeline",
      chart_type:       "funnel",
      dashboard_use:    "landscape",
      slide_use:        "cross_category_convergence",
      confidence:       "medium",
      insufficient_data:false,
      caveat_if_any:    "Maturity stages reflect classification within collected sources, not population estimates.",
      chart_data: {
        items: [
          { key: "research_only",           label: "Research Only",         count: 22 },
          { key: "proof_of_concept",        label: "Proof of Concept",      count: 15 },
          { key: "limited_operational_use", label: "Limited Operational",   count: 8 },
          { key: "active_operational_use",  label: "Active Operational",    count: 4 },
          { key: "mainstream_operational_use",label:"Mainstream",           count: 2 },
        ],
      },
      supports_claim_types: ["capability_shift_claim", "outlook"],
      supports_analytics_evidence_ids: ["ae_llm_maturity", "ae_tai_maturity"],
      interactive_drilldown: { click_target_type: "source_list", linked_source_ids: [] },
    },
    {
      visualization_id: "vs_evidence_strength",
      title:            "Evidence Strength by Category",
      chart_type:       "matrix_table",
      dashboard_use:    "overview,evidence_explorer",
      slide_use:        "evidence_coverage",
      confidence:       "high",
      insufficient_data:false,
      caveat_if_any:    null,
      chart_data: {
        columns: [
          { key: "strong",   label: "Strong" },
          { key: "usable",   label: "Usable" },
          { key: "context",  label: "Context" },
          { key: "archive",  label: "Archive" },
        ],
        rows: [
          { key: "llm_threats",            label: "LLM Threats",    values: [5, 12, 8, 3] },
          { key: "agentic_ai_threats",     label: "Agentic AI",     values: [2, 7, 5, 3] },
          { key: "traditional_ai_threats", label: "Traditional AI", values: [1, 5, 4, 2] },
          { key: "ai_enabled_threats",     label: "AI-Enabled",     values: [0, 1, 3, 1] },
        ],
      },
      supports_claim_types: ["confidence_assessment", "evidence_gap"],
      supports_analytics_evidence_ids: [],
      interactive_drilldown: { click_target_type: "evidence_list", linked_evidence_ids: ["ev_src1_001","ev_src2_001"] },
    },
    {
      visualization_id: "vs_ai_enabled_overlay",
      title:            "AI-Enabled Overlay by Category",
      chart_type:       "stacked_bar",
      dashboard_use:    "landscape",
      slide_use:        "category_insight",
      confidence:       "medium",
      insufficient_data:false,
      caveat_if_any:    "Overlay roles are not mutually exclusive — one source can carry multiple roles.",
      chart_data: {
        months: ["llm_threats", "agentic_ai_threats", "traditional_ai_threats"],
        stacks: [
          { key: "attack_tool",     label: "AI as Attack Tool",      values: [8, 5, 3] },
          { key: "attack_target",   label: "AI as Attack Target",    values: [14, 7, 6] },
          { key: "defense_control", label: "AI as Defense Control",  values: [3, 2, 1] },
          { key: "infra_dep",       label: "AI as Infrastructure",   values: [5, 8, 2] },
        ],
      },
      supports_claim_types: ["frequency_claim", "exposure_shift_claim"],
      supports_analytics_evidence_ids: [],
      interactive_drilldown: { click_target_type: "evidence_list", linked_evidence_ids: [] },
    },
    {
      visualization_id: "vs_taxonomy_heatmap",
      title:            "Primary Threat Tag Distribution",
      chart_type:       "heatmap_table",
      dashboard_use:    "landscape",
      slide_use:        "threat_tag_distribution",
      confidence:       "medium",
      insufficient_data:false,
      caveat_if_any:    "Taxonomy tags are not exhaustive — untagged sources contribute to category counts but not this heatmap.",
      chart_data: {
        columns: [
          { key: "llm_threats",            label: "LLM" },
          { key: "agentic_ai_threats",     label: "Agentic" },
          { key: "traditional_ai_threats", label: "Traditional" },
        ],
        rows: [
          { key: "LLM.PI.01", label: "Prompt Injection",      values: [14, 2, 0] },
          { key: "LLM.PI.02", label: "RAG Poisoning",         values: [8,  1, 0] },
          { key: "ASI.TC.01", label: "Tool-Call Injection",   values: [2,  6, 0] },
          { key: "ASI.MCP.01",label: "MCP Abuse",             values: [1,  5, 0] },
          { key: "TAI.DP.01", label: "Data Poisoning",        values: [0,  1, 7] },
          { key: "TAI.BK.01", label: "Model Backdoor",        values: [0,  0, 4] },
        ],
      },
      supports_claim_types: ["frequency_claim", "category_insight"],
      supports_analytics_evidence_ids: [],
      interactive_drilldown: { click_target_type: "evidence_list", linked_evidence_ids: [] },
    },
  ],

  // ── Analytics Evidence (L5B) ───────────────────────────────────────────────
  analytics_evidence: [
    {
      analytics_evidence_id: "ae_llm_atk_vec",
      metric_type:           "frequency_distribution",
      finding:               "Within the collected corpus, prompt_injection is the most frequent attack vector (19 sources, 38% of vector-tagged sources).",
      domain:                "llm_threats",
      source_ids:            ["src_nist_001","src_anthropic_001","src_cisa_001"],
      confidence:            "medium",
      caveat_if_any:         "Attack vector frequency reflects extraction from parsed sources, not real-world prevalence.",
      supports_claim_types:  ["frequency_claim", "category_insight"],
      recommended_visualization_ids: ["vs_attack_vector_freq"],
    },
    {
      analytics_evidence_id: "ae_llm_maturity",
      metric_type:           "maturity_distribution",
      finding:               "Within the collected corpus, 12 LLM threat sources show active/limited operational status — highest among all categories.",
      domain:                "llm_threats",
      source_ids:            ["src_nist_001","src_anthropic_001"],
      confidence:            "high",
      caveat_if_any:         null,
      supports_claim_types:  ["capability_shift_claim", "adoption_claim"],
      recommended_visualization_ids: ["vs_maturity_funnel"],
    },
    {
      analytics_evidence_id: "ae_agt_atk_vec",
      metric_type:           "frequency_distribution",
      finding:               "Within the collected corpus, tool_hijacking and mcp_abuse vectors appear in 8 and 6 agentic sources respectively.",
      domain:                "agentic_ai_threats",
      source_ids:            ["src_arxiv_001"],
      confidence:            "medium",
      caveat_if_any:         "Small corpus (17 agentic sources) — distributions directional only.",
      supports_claim_types:  ["frequency_claim", "capability_shift_claim"],
      recommended_visualization_ids: ["vs_attack_vector_freq"],
    },
    {
      analytics_evidence_id: "ae_tai_maturity",
      metric_type:           "maturity_distribution",
      finding:               "Within the collected corpus, 6 of 12 traditional AI threat sources are at research or PoC stage — not yet operational.",
      domain:                "traditional_ai_threats",
      source_ids:            ["src_deepmind_001"],
      confidence:            "medium",
      caveat_if_any:         null,
      supports_claim_types:  ["capability_shift_claim", "outlook"],
      recommended_visualization_ids: ["vs_maturity_funnel"],
    },
  ],

  // ── Source Index ───────────────────────────────────────────────────────────
  source_index: {
    "src_nist_001":      { source_id: "src_nist_001",     title: "Prompt Injection in Enterprise LLM Deployments", publisher: "NIST",          url: "https://nist.gov/example", date_published: "2026-05-12", source_type: "incident",          trust_tier: "primary" },
    "src_anthropic_001": { source_id: "src_anthropic_001",title: "LLM Attack Patterns Analysis 2025",              publisher: "Anthropic",      url: "https://anthropic.com/research", date_published: "2026-04-28", source_type: "research_finding",  trust_tier: "primary" },
    "src_cisa_001":      { source_id: "src_cisa_001",     title: "AI Governance Landscape Report Q1 2026",         publisher: "CISA",           url: "https://cisa.gov/example", date_published: "2026-05-20", source_type: "governance_signal", trust_tier: "primary" },
    "src_arxiv_001":     { source_id: "src_arxiv_001",    title: "MCP Server Hijacking PoCs",                      publisher: "arXiv",          url: "https://arxiv.org/abs/example", date_published: "2026-05-08", source_type: "research_finding",  trust_tier: "high" },
    "src_deepmind_001":  { source_id: "src_deepmind_001", title: "Data Poisoning of HuggingFace Models",           publisher: "Google DeepMind",url: "https://deepmind.google/example", date_published: "2026-05-03", source_type: "research_finding",  trust_tier: "primary" },
    "src_misc_001":      { source_id: "src_misc_001",     title: "Jailbreak Market Analysis 2026",                 publisher: "Security Vendor",url: "https://example.com/jailbreaks", date_published: "2026-04-15", source_type: "threat_intelligence",trust_tier: "medium" },
  },

  // ── Evidence Index (L5A rawfact items) ─────────────────────────────────────
  evidence_index: {
    "ev_src1_001": {
      evidence_id:     "ev_src1_001",
      source_id:       "src_nist_001",
      evidence_type:   "incident_report",
      evidence_strength:"strong",
      fact:            "3 documented incidents confirmed where indirect prompt injection via poisoned RAG documents bypassed enterprise LLM guardrails.",
      source_quote:    "In all three cases, the attacker inserted malicious instructions into documents retrieved by the RAG pipeline, causing the LLM to execute unintended actions.",
      entities:        ["ChatGPT Enterprise","Bing Chat","RAG"],
      numbers:         ["3"],
      claim_ids:       ["cl_llm_001"],
    },
    "ev_src2_001": {
      evidence_id:     "ev_src2_001",
      source_id:       "src_anthropic_001",
      evidence_type:   "research_finding",
      evidence_strength:"usable",
      fact:            "Indirect injection via RAG documents was observed in 12 of 50 evaluated production LLM deployments.",
      source_quote:    "Of the 50 deployments evaluated, 12 showed evidence of successful indirect injection via document-embedded instructions.",
      entities:        ["RAG pipeline","production LLM"],
      numbers:         ["12","50"],
      claim_ids:       ["cl_llm_001","cl_llm_002"],
    },
    "ev_src3_001": {
      evidence_id:     "ev_src3_001",
      source_id:       "src_arxiv_001",
      evidence_type:   "exploit_demonstration",
      evidence_strength:"usable",
      fact:            "Tool-call injection demonstrated across 4 independent proof-of-concept implementations targeting MCP servers.",
      source_quote:    "Four independent research teams demonstrated tool-call injection via malicious MCP server responses within the evaluation window.",
      entities:        ["MCP","Claude","tool_call"],
      numbers:         ["4"],
      claim_ids:       ["cl_agt_001"],
    },
    "ev_src4_001": {
      evidence_id:     "ev_src4_001",
      source_id:       "src_deepmind_001",
      evidence_type:   "vulnerability_disclosure",
      evidence_strength:"usable",
      fact:            "Researchers demonstrated backdoor injection into 3 popular open-source models via compromised training data pipelines, requiring less than 0.01% poisoned samples.",
      source_quote:    "The attack required less than 0.01% poisoned samples to reliably trigger the backdoor at inference time.",
      entities:        ["HuggingFace","training pipeline","backdoor"],
      numbers:         ["3","0.01%"],
      claim_ids:       ["cl_tai_001"],
    },
    "ev_src5_001": {
      evidence_id:     "ev_src5_001",
      source_id:       "src_cisa_001",
      evidence_type:   "policy_or_governance",
      evidence_strength:"context",
      fact:            "CISA issued new guidance on LLM deployment security, citing prompt injection as a top risk for federal agencies.",
      source_quote:    "Prompt injection represents the most immediate operational risk for federal LLM deployments in production environments.",
      entities:        ["CISA","federal agencies","LLM"],
      numbers:         [],
      claim_ids:       ["cl_llm_003"],
    },
    "ev_src6_001": {
      evidence_id:     "ev_src6_001",
      source_id:       "src_arxiv_001",
      evidence_type:   "research_finding",
      evidence_strength:"context",
      fact:            "Researchers propose a multi-agent injection framework where LLM-to-LLM prompt smuggling can propagate across orchestration layers without detection.",
      source_quote:    "Our framework demonstrates that prompt smuggling between agent nodes evades per-node safety filters in all tested configurations.",
      entities:        ["multi-agent","LLM orchestration"],
      numbers:         [],
      claim_ids:       ["cl_agt_002"],
    },
    "ev_src7_001": {
      evidence_id:     "ev_src7_001",
      source_id:       "src_misc_001",
      evidence_type:   "adversary_adoption",
      evidence_strength:"usable",
      fact:            "Underground forums show emerging jailbreak-as-a-service offerings, with modular prompts sold by technique family.",
      source_quote:    "Multiple threat intelligence sources report emerging commercial marketplaces offering modular jailbreak prompts for major model families.",
      entities:        ["jailbreak marketplace","underground forums"],
      numbers:         [],
      claim_ids:       ["cl_llm_002"],
    },
  },

  // ── External Evidence Index (L5C) ──────────────────────────────────────────
  external_evidence_index: {
    "extev_cisa_001": {
      external_evidence_id: "extev_cisa_001",
      evidence_type:    "regulatory_reference",
      finding:          "CISA classifies prompt injection as top operational risk for federal LLM deployments.",
      publisher:        "CISA",
      url:              "https://cisa.gov/advisory/llm-2026",
      source_quality:   "authoritative",
      freshness_status: "current",
      confidence:       "high",
      source_quote:     "Prompt injection is identified as the highest-priority risk for federal agencies deploying large language models.",
      caveat_if_any:    "Governance signal — confirms regulatory concern but cannot confirm adversary exploitation alone.",
      claim_ids:        ["cl_llm_001","cl_llm_003"],
    },
  },
};

// ── Legacy exports (backward compat with old components) ────────────────────────
export const THREAT_CATEGORIES   = MONTHLY_DASHBOARD.categories;
export const EARLY_SIGNALS       = MONTHLY_DASHBOARD.early_signals;
export const EVIDENCE_ITEMS      = Object.values(MONTHLY_DASHBOARD.evidence_index);
export const COVERAGE_GAPS       = MONTHLY_DASHBOARD.categories
  .filter((c) => c.assessment_status === "evidence_insufficient" || c.confidence === "low")
  .map((c) => ({ category: c.id, gap: c.top_signal, severity: c.confidence === "low" ? "high" : "medium" }));

export const REPORT_PERIOD = {
  label:            MONTHLY_DASHBOARD.summary.period_label,
  start_date:       MONTHLY_DASHBOARD.summary.date_range.start,
  end_date:         MONTHLY_DASHBOARD.summary.date_range.end,
  total_sources:    MONTHLY_DASHBOARD.summary.total_sources,
  sources_validated:MONTHLY_DASHBOARD.summary.sources_validated,
};

export const AI_ENABLED_OVERLAY_EXAMPLES = [
  { role: "attack_tool",   category: "llm_threats",        count: 8,  example: "AI-generated phishing targeting LLM users" },
  { role: "attack_target", category: "llm_threats",        count: 14, example: "LLM safety system as attack surface" },
  { role: "infra_dep",     category: "agentic_ai_threats", count: 8,  example: "AI orchestration layer as dependency" },
];

export const VISUAL_EVIDENCE_ITEMS = [];
