/**
 * Layer 5a.2 — Evidence Extraction Profiles
 *
 * Returns per-source-type extraction profiles that guide what evidence items should
 * be extracted, how many, and what to prioritise. Fully deterministic — no LLM calls.
 *
 * Input:  source_type string
 * Output: extraction profile { source_type, allowed_evidence_types, prioritize, max_items }
 */

// ── Canonical evidence types (extractor-level only) ──────────────���────────────
//
// These are the ONLY types the LLM extractor may emit. They represent concrete,
// source-grounded facts at either raw_fact or derived_observation abstraction level.
//
// INTENTIONALLY EXCLUDED from this list (synthesis layer only):
//   strategic_signal   — must be generated by L6 from multiple corroborating items
//   ecosystem_shift    — synthesis output unless source explicitly documents one
//   trust_boundary_shift — synthesis output unless source describes a concrete permission change
//
// INTENTIONALLY REMOVED (replaced by metadata fields on items):
//   timeline_event — use event_date / date_range fields on the relevant item
//   statistic      — attach as metric{} to the relevant evidence item; standalone stats are noise

export const ALL_EVIDENCE_TYPES = [
  "incident_event",          // Confirmed real-world attack, breach, or harmful deployment
  "vulnerability_fact",      // Disclosed weakness in a system, model, or protocol
  "exploit_chain",           // Specific ordered exploitation sequence tied to a concrete target
  "attack_method",           // General reusable technique or procedure (not target-specific)
  "threat_actor_activity",   // Observed behavior attributed to a named actor or campaign
  "adversary_adoption",      // Signal that real adversaries are using or testing a capability
  "capability_delta",        // Explicit comparison showing capability expansion (requires before/after)
  "research_result",         // Finding from controlled research — what the study found
  "benchmark_result",        // Measured performance value (success rate, score, etc.)
  "societal_harm",           // Real-world harm caused by AI-enabled activity
  "governance_action",       // Policy, regulation, advisory, or official guidance issued
  "defensive_control",       // Mitigation, detection rule, or protective measure
  "mitigation",              // Recommended or deployed countermeasure
  "infrastructure_dependency", // New or risky dependency in the AI supply/delivery chain
];

// ── Evidence class (semantic grouping, not importance) ────────────────────────
// Assigned deterministically from evidence_type during normalization.

export const EVIDENCE_TYPE_TO_CLASS = {
  incident_event:           "observational",
  vulnerability_fact:       "technical",
  exploit_chain:            "technical",
  attack_method:            "technical",
  threat_actor_activity:    "adversary_activity",
  adversary_adoption:       "adversary_activity",
  capability_delta:         "technical",
  research_result:          "research",
  benchmark_result:         "research",
  societal_harm:            "harm",
  governance_action:        "governance",
  defensive_control:        "defensive",
  mitigation:               "defensive",
  infrastructure_dependency:"infrastructure",
};

// ── Abstraction level ─────────────────────────────────────────────��───────────
// raw_fact          — source directly states it; single hop from text to item
// derived_observation — requires inference or comparison across statements
// synthesis_candidate �� should only appear after L6 corroboration (not extractor-level)

export const EVIDENCE_TYPE_TO_ABSTRACTION = {
  incident_event:            "raw_fact",
  vulnerability_fact:        "raw_fact",
  exploit_chain:             "raw_fact",
  attack_method:             "derived_observation",
  threat_actor_activity:     "raw_fact",
  adversary_adoption:        "raw_fact",
  capability_delta:          "derived_observation",
  research_result:           "raw_fact",
  benchmark_result:          "raw_fact",
  societal_harm:             "raw_fact",
  governance_action:         "raw_fact",
  defensive_control:         "raw_fact",
  mitigation:                "raw_fact",
  infrastructure_dependency: "derived_observation",
};

// ── Source type → allowed evidence types ──────────────────────────────────────

export const SOURCE_TYPE_EVIDENCE_TYPES = {
  incident: [
    "incident_event", "attack_method", "threat_actor_activity",
    "vulnerability_fact", "societal_harm",
  ],
  vulnerability: [
    "vulnerability_fact", "exploit_chain", "mitigation",
  ],
  exploit_disclosure: [
    "exploit_chain", "attack_method", "vulnerability_fact", "capability_delta", "mitigation",
  ],
  threat_intelligence: [
    "threat_actor_activity", "attack_method", "adversary_adoption",
    "capability_delta",
  ],
  adversary_adoption_signal: [
    "adversary_adoption", "threat_actor_activity", "attack_method",
    "capability_delta",
  ],
  research_finding: [
    "research_result", "attack_method", "capability_delta",
    "vulnerability_fact", "mitigation",
  ],
  capability_demonstration: [
    "capability_delta", "attack_method", "benchmark_result", "societal_harm",
  ],
  benchmark_evaluation: [
    "benchmark_result", "capability_delta", "research_result",
    "attack_method", "societal_harm",
  ],
  societal_harm_signal: [
    "societal_harm", "incident_event", "adversary_adoption",
  ],
  governance_signal: [
    "governance_action", "mitigation",
  ],
  defensive_capability: [
    "defensive_control", "mitigation", "benchmark_result",
  ],
  attack_surface_signal: [
    "infrastructure_dependency", "capability_delta",
  ],
  unknown: [],
};

// ── Anti-hallucination extraction rules ───────────────────────────────────────
// Injected into every LLM extraction prompt. Applies across all source types.

export const UNIVERSAL_EXTRACTION_RULES = `
UNIVERSAL RULES (apply to every item regardless of source type):
- Do NOT extract generic background claims ("AI is transforming...", "threats are increasing...")
- Do NOT extract unsupported predictions or vague future risk statements
- Do NOT extract marketing language or vendor superlatives without concrete evidence
- Do NOT extract summaries of what the source does ("this paper proposes...", "the report describes...")
- Every item MUST include a verbatim source_quote that directly grounds the fact
- Every item MUST include a type_justification: one sentence explaining why this fact qualifies for its evidence_type
- If you cannot find a verbatim quote supporting the claim, do NOT extract the item
- If the fact is too general to fact-check against the source, do NOT extract it

TYPE-SPECIFIC RULES:
exploit_chain:
  ONLY use when the source describes a specific ORDERED SEQUENCE of steps (step 1 → step 2...)
  exploiting a concrete weakness in an identified system or target.
  A general description of how a class of attacks works is attack_method, not exploit_chain.

attack_method:
  A GENERAL, REUSABLE technique or procedure applicable across multiple targets.
  If the source describes a single specific ordered attack against a single target, use exploit_chain.
  Do NOT extract vague descriptions like "attackers can use AI to improve phishing".

capability_delta:
  ONLY extract if the source EXPLICITLY compares current capability against prior capability
  AND shows measurable improvement, scale expansion, or new operational feasibility.
  "Researchers achieved X% success" alone is NOT a capability_delta — use research_result.
  "GPT-4 can now bypass guardrails that GPT-3.5 could not" IS a capability_delta.

adversary_adoption:
  ONLY extract when the source provides direct evidence that real adversaries (named or described
  threat actors, observed campaigns) are actively using or piloting a capability.
  Predictions or researcher speculation are NOT adversary_adoption.

infrastructure_dependency:
  ONLY extract when the source explicitly identifies a specific dependency, concentration risk,
  or trust boundary that creates exploitable exposure.
  Do NOT extract generic statements about AI adoption or ecosystem growth.

strategic_signal / ecosystem_shift / trust_boundary_shift:
  These are synthesis-layer outputs. Do NOT emit them from the extractor.
  They must be generated by the analysis layer (L6) from multiple corroborating evidence items.
  If you feel the source implies a strategic shift, extract the concrete underlying facts instead.
`.trim();

// ── Per-source-type extraction rules ─────────────────────────────────────────

export const SOURCE_TYPE_EXTRACTION_RULES = {
  incident: "Focus on the concrete attack sequence, victim identity/sector, attacker method, and confirmed damage or impact. Extract only what is directly stated — do not infer broader significance.",
  vulnerability: "Focus on the specific weakness: affected system/version, how it is exploited (if known), patch status, and blast radius. Do not speculate about unexplored attack paths.",
  exploit_disclosure: "Focus on the actual exploit mechanics. Require ordered steps for exploit_chain. Only use capability_delta if the source explicitly states this attack was not previously possible.",
  threat_intelligence: "Focus on observed TTPs, confirmed actor behavior, and attribution evidence. Do not extract inferred or speculative actor capabilities as threat_actor_activity.",
  adversary_adoption_signal: "Require direct evidence of adversary use (named actor, campaign, observed behavior). Researcher speculation or proof-of-concept alone is NOT adversary adoption.",
  research_finding: "Focus on what was empirically demonstrated: systems tested, conditions, success rate, limitations. Do not promote theoretical results to capability_delta unless the comparison with prior state is explicit.",
  capability_demonstration: "Only use capability_delta if the paper shows a new capability ceiling. Use benchmark_result for measured performance values. Do not extract 'potential' improvements.",
  benchmark_evaluation: "Require numeric values (ASR, score, rate) for benchmark_result items. Attach measurements as metric{}. Do not extract qualitative assessments without underlying numbers.",
  societal_harm_signal: "Focus on the specific harm, affected population, and the AI capability that enabled it. Do not extract vague statements about AI misuse potential.",
  governance_signal: "Focus on what was mandated, recommended, or prohibited — and by whom. Do not produce attack-type evidence items from governance sources.",
  defensive_capability: "Focus on concrete mitigations: what they address, deployment readiness, measured effectiveness. Do not produce attack-type evidence from defensive sources.",
  attack_surface_signal: "Focus on concrete dependencies or trust-boundary changes with exploitable exposure. Do not extract ecosystem_shift or strategic_signal — these are synthesis outputs.",
};

// ── Profiles ──────────────────────────────────────────────────────────────────

export const EXTRACTION_PROFILES = {
  incident: {
    source_type:            "incident",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.incident,
    prioritize:             ["confirmed impact", "victim/sector", "attacker method", "scale", "institutional response"],
    max_items:              5,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.incident,
  },
  vulnerability: {
    source_type:            "vulnerability",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.vulnerability,
    prioritize:             ["affected system", "exploitability", "patch status", "exploitation status", "blast radius"],
    max_items:              4,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.vulnerability,
  },
  exploit_disclosure: {
    source_type:            "exploit_disclosure",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.exploit_disclosure,
    prioritize:             ["reproducibility", "required access", "exploit chain steps", "public tooling", "operational realism"],
    max_items:              4,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.exploit_disclosure,
  },
  threat_intelligence: {
    source_type:            "threat_intelligence",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.threat_intelligence,
    prioritize:             ["observed TTPs", "campaign scope", "attribution confidence", "active exploitation", "sector targeting"],
    max_items:              4,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.threat_intelligence,
  },
  adversary_adoption_signal: {
    source_type:            "adversary_adoption_signal",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.adversary_adoption_signal,
    prioritize:             ["who is adopting", "what capability", "direct evidence of use", "spread trajectory"],
    max_items:              3,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.adversary_adoption_signal,
  },
  research_finding: {
    source_type:            "research_finding",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.research_finding,
    prioritize:             ["what was demonstrated", "systems tested", "success rate or metric", "operationalization likelihood", "limitations stated by authors"],
    max_items:              4,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.research_finding,
  },
  capability_demonstration: {
    source_type:            "capability_demonstration",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.capability_demonstration,
    prioritize:             ["what is now possible", "autonomy level", "operational completeness", "prior comparison if stated"],
    max_items:              3,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.capability_demonstration,
  },
  benchmark_evaluation: {
    source_type:            "benchmark_evaluation",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.benchmark_evaluation,
    prioritize:             ["key metric (ASR/score/rate)", "models/systems tested", "attack method used", "capability ceiling established", "trajectory signal if stated"],
    max_items:              3,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.benchmark_evaluation,
  },
  societal_harm_signal: {
    source_type:            "societal_harm_signal",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.societal_harm_signal,
    prioritize:             ["harm type", "affected population or scale", "AI capability that enabled harm", "institutional or legal response"],
    max_items:              3,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.societal_harm_signal,
  },
  governance_signal: {
    source_type:            "governance_signal",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.governance_signal,
    prioritize:             ["issuing authority", "affected sectors", "specific requirement or prohibition", "compliance timeline"],
    max_items:              2,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.governance_signal,
  },
  defensive_capability: {
    source_type:            "defensive_capability",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.defensive_capability,
    prioritize:             ["gap addressed", "deployment readiness", "effectiveness evidence", "limitations"],
    max_items:              2,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.defensive_capability,
  },
  attack_surface_signal: {
    source_type:            "attack_surface_signal",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.attack_surface_signal,
    prioritize:             ["what dependency or trust boundary is being introduced", "scale of adoption", "concrete exploitable exposure", "horizon relevance (3–12 months)"],
    max_items:              2,
    extraction_rules:       SOURCE_TYPE_EXTRACTION_RULES.attack_surface_signal,
  },
  unknown: {
    source_type:            "unknown",
    allowed_evidence_types: SOURCE_TYPE_EVIDENCE_TYPES.unknown,
    prioritize:             [],
    max_items:              0,
    extraction_rules:       "Do not extract anything from unknown source types.",
  },
};

// ── Public API ────────────────────────────────────────────────────────────────

export function getExtractionProfile(sourceType) {
  return EXTRACTION_PROFILES[sourceType] ?? EXTRACTION_PROFILES.unknown;
}

/**
 * Get the extraction profile for a source type, adjusted for concreteness.
 *
 * The concreteness_class from evidenceEligibility sets an extraction_depth_hint
 * that modifies max_items:
 *   deep     — +2 items (concrete content warrants deeper extraction)
 *   standard — no change
 *   shallow  — -1 items (vague/marketing content warrants shallower extraction)
 *
 * @param {string} sourceType
 * @param {string} [depthHint="standard"] - from evidence_eligibility.extraction_depth_hint
 * @returns {object} extraction profile with adjusted max_items
 */
export function getExtractionProfileWithDepth(sourceType, depthHint = "standard") {
  const profile = getExtractionProfile(sourceType);
  if (!profile || profile.max_items === 0) return profile;

  let maxItems = profile.max_items;
  if (depthHint === "deep")    maxItems = Math.min(maxItems + 2, 7);
  if (depthHint === "shallow") maxItems = Math.max(maxItems - 1, 1);

  return { ...profile, max_items: maxItems };
}

export function applyExtractionProfiles(sources) {
  return sources.map((source) => {
    const depthHint = source.evidence_eligibility?.extraction_depth_hint || "standard";
    return {
      ...source,
      extraction_profile: getExtractionProfileWithDepth(source.source_type || "unknown", depthHint),
    };
  });
}
