/**
 * Source registry — active RSS/Atom connectors for ingestion.
 *
 * Only enabled feeds live here. Feeds that were trialled and removed, or that
 * have dead RSS URLs, are deleted rather than kept disabled — the git history
 * records what was tried and why it was removed.
 *
 * source_type values MUST be from the controlled vocabulary in
 * lib/config/sourceTypes.js. Layer 3 re-classifies at ingest time, but setting
 * the right value here avoids redundant work.
 *
 * trust_tier scale:
 *   primary — government agencies, AI labs (Anthropic, OpenAI, NIST, CISA)
 *   high    — established security vendors, reputable research orgs, known researchers
 *   medium  — security journalism, smaller vendors with mixed content quality
 *   low     — high-volume aggregators; classifier discards most output
 */

export const SOURCE_REGISTRY = [

  // ── Government + primary authorities ─────────────────────────────────────────

  {
    name: "CISA Advisories",
    publisher: "CISA",
    type: "rss",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
  },
  {
    name: "NCSC UK",
    publisher: "UK National Cyber Security Centre",
    type: "rss",
    url: "https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
  },
  {
    name: "NIST AI",
    publisher: "NIST",
    type: "rss",
    url: "https://www.nist.gov/blogs/cybersecurity-insights/rss.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
  },
  {
    name: "Google Project Zero",
    publisher: "Google Project Zero",
    type: "atom",
    url: "https://googleprojectzero.blogspot.com/feeds/posts/default",
    source_type: "exploit_disclosure",
    trust_tier: "primary",
    retrieval_method: "official_atom",
  },

  // ── AI lab research ───────────────────────────────────────────────────────────

  {
    name: "OpenAI Blog",
    publisher: "OpenAI",
    type: "rss",
    url: "https://openai.com/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_rss",
  },
  {
    name: "Transformer Circuits (Anthropic Interpretability)",
    publisher: "Anthropic",
    type: "atom",
    url: "https://transformer-circuits.pub/feed.xml",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_atom",
  },
  {
    name: "Google Security Blog",
    publisher: "Google",
    type: "atom",
    url: "https://security.googleblog.com/feeds/posts/default",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
  },
  {
    name: "Google Research Blog",
    publisher: "Google Research",
    type: "rss",
    url: "https://research.google/blog/rss/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Hugging Face Blog",
    publisher: "Hugging Face",
    type: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
    // AI model registry incidents and ML ecosystem security frequently originate here.
  },

  // ── AI-specific security research ────────────────────────────────────────────

  {
    name: "Embrace The Red",
    publisher: "Wunderwuzzi (Embrace The Red)",
    type: "rss",
    url: "https://embracethered.com/blog/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Adversa AI Research",
    publisher: "Adversa AI",
    type: "rss",
    url: "https://adversa.ai/rss.xml",
    // Healed 2026-07-26 via autodiscovery: original URL was https://adversa.ai/blog/feed/
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "AVID AI Vulnerability Blog",
    publisher: "AVID (AI Vulnerability Database)",
    type: "rss",
    url: "https://news.google.com/rss/search?q=site:avidml.org&hl=en-US&gl=US&ceid=US:en",
    // Healed 2026-07-26 via google_news: original URL was https://avidml.org/blog/index.xml
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "ML Safety Newsletter",
    publisher: "Center for AI Safety",
    type: "rss",
    url: "https://newsletter.mlsafety.org/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Palisade Research",
    publisher: "Palisade Research",
    type: "atom",
    url: "https://palisaderesearch.org/feed.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
  },
  {
    name: "AI Incident Database",
    publisher: "AI Incident Database",
    type: "rss",
    url: "https://incidentdatabase.ai/rss.xml",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: false,
  },
  {
    name: "Protect AI Threat Research",
    publisher: "Protect AI",
    type: "rss",
    url: "https://protectai.com/threat-research/rss.xml",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: false,  // 404 — protectai.com removed all RSS feeds (confirmed Jul 2026)
  },
  {
    name: "Protect AI Blog",
    publisher: "Protect AI",
    type: "rss",
    url: "https://protectai.com/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: false,  // 404 — protectai.com removed all RSS feeds (confirmed Jul 2026)
  },
  {
    name: "Joseph Thacker (rez0)",
    publisher: "Joseph Thacker",
    type: "atom",
    url: "https://josephthacker.com/feed.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
  },
  {
    name: "Kai Greshake",
    publisher: "Kai Greshake",
    type: "rss",
    url: "https://kai-greshake.de/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    // Author of the seminal prompt injection paper.
  },
  {
    name: "Promptfoo Blog",
    publisher: "Promptfoo",
    type: "rss",
    url: "https://www.promptfoo.dev/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Knostic Blog",
    publisher: "Knostic",
    type: "rss",
    url: "https://www.knostic.ai/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "rss",
  },

  // ── Agentic AI security: incident-first vendors ────────────────────────────

  {
    name: "Sysdig Security Blog",
    publisher: "Sysdig",
    type: "rss",
    url: "https://sysdig.com/blog/rss.xml",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    // Primary source for AI agent exploitation incidents: agentic ransomware,
    // LMDeploy SSRF, Langflow post-KEV exploitation. Runs live honeypots.
  },
  {
    name: "Aikido Security Blog",
    publisher: "Aikido Security",
    type: "rss",
    url: "https://www.aikido.dev/blog/rss.xml",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    // npm/PyPI supply chain analysis: package worm lineage, TeamPCP cascade.
  },
  {
    name: "StepSecurity Blog",
    publisher: "StepSecurity",
    type: "rss",
    url: "https://www.stepsecurity.io/blog/rss.xml",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    // First reporter on several GitHub Actions supply chain incidents.
  },
  {
    name: "Noma Security Blog",
    publisher: "Noma Security",
    type: "rss",
    url: "https://noma.security/feed/",
    source_type: "research_finding",
    trust_tier: "medium",
    retrieval_method: "official_rss",
    // Agentic AI security research: GitLost, WriteOut, CrewAI cross-tenant issues.
  },
  {
    name: "Cato Networks Security Blog",
    publisher: "Cato Networks",
    type: "rss",
    url: "https://www.catonetworks.com/blog/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
    // Cato AI Labs: AI coding agent security research, zero-click RCE disclosures.
  },
  {
    name: "Endor Labs Blog",
    publisher: "Endor Labs",
    type: "rss",
    url: "https://www.endorlabs.com/blog/rss.xml",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    // Supply chain + AI infrastructure CVEs via AI SAST tooling.
  },
  // SAND Security Blog removed — their blog is a React SPA with no RSS feed.

  // ── Enterprise security vendors ────────────────────────────────────────────

  {
    name: "Microsoft Security Blog",
    publisher: "Microsoft",
    type: "rss",
    url: "https://www.microsoft.com/en-us/security/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Microsoft MSTIC",
    publisher: "Microsoft Threat Intelligence",
    type: "rss",
    url: "https://www.microsoft.com/en-us/security/blog/topic/threat-intelligence/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Unit 42 Threat Research",
    publisher: "Palo Alto Networks Unit 42",
    type: "rss",
    url: "https://unit42.paloaltonetworks.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "CrowdStrike Blog",
    publisher: "CrowdStrike",
    type: "rss",
    url: "https://www.crowdstrike.com/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Recorded Future Blog",
    publisher: "Recorded Future",
    type: "rss",
    url: "https://www.recordedfuture.com/feed",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Check Point Research",
    publisher: "Check Point Research",
    type: "rss",
    url: "https://research.checkpoint.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Talos Intelligence Blog",
    publisher: "Cisco Talos",
    type: "rss",
    url: "https://blog.talosintelligence.com/rss/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "SentinelLabs Research",
    publisher: "SentinelOne",
    type: "rss",
    url: "https://www.sentinelone.com/labs/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    // news.sophos.com is DNS-dead; www.sophos.com is geo/IP restricted from cloud.
    // Use Google News RSS for Sophos threat research coverage instead.
    name: "Sophos X-Ops",
    publisher: "Sophos",
    type: "rss",
    url: "https://news.google.com/rss/search?q=site:sophos.com+threat+research&hl=en-US&gl=US&ceid=US:en",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Proofpoint Threat Research",
    publisher: "Proofpoint",
    type: "rss",
    url: "https://www.proofpoint.com/us/rss.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Elastic Security Labs",
    publisher: "Elastic",
    type: "rss",
    url: "https://www.elastic.co/security-labs/rss/feed.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "ESET WeLiveSecurity",
    publisher: "ESET",
    type: "rss",
    url: "https://www.welivesecurity.com/en/rss/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Trend Micro Research",
    publisher: "Trend Micro",
    type: "rss",
    url: "https://feeds.feedburner.com/TrendMicroResearch",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    // Old feeds.trendmicro.com host is dead; FeedBurner mirror is live.
  },
  {
    name: "Malwarebytes Labs",
    publisher: "Malwarebytes",
    type: "rss",
    url: "https://www.malwarebytes.com/blog/feed/index.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Flashpoint Intelligence",
    publisher: "Flashpoint",
    type: "rss",
    url: "https://flashpoint.io/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Risky Business News",
    publisher: "Risky Business",
    type: "rss",
    url: "https://risky.biz/feeds/risky-business-news/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Zscaler ThreatLabz",
    publisher: "Zscaler ThreatLabz",
    type: "rss",
    url: "https://www.zscaler.com/blogs/feeds",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Rapid7 Threat Intelligence",
    publisher: "Rapid7",
    type: "rss",
    url: "https://www.rapid7.com/blog/rss/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },

  // ── Vulnerability research ────────────────────────────────────────────────────

  {
    name: "Cisco Security Advisories",
    publisher: "Cisco",
    type: "rss",
    url: "https://feeds.feedburner.com/CiscoSecurityAdvisory",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "SANS Internet Storm Center",
    publisher: "SANS ISC",
    type: "rss",
    url: "https://isc.sans.edu/rssfeed_full.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: false,  // 403 from all datacenter IPs regardless of UA (confirmed Jul 2026)
  },
  {
    name: "Bishop Fox Blog",
    publisher: "Bishop Fox",
    type: "rss",
    url: "https://bishopfox.com/blog/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Trail of Bits Blog",
    publisher: "Trail of Bits",
    type: "rss",
    url: "https://blog.trailofbits.com/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Wiz Research Blog",
    publisher: "Wiz",
    type: "rss",
    url: "https://www.wiz.io/blog/rss.xml",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Snyk Security Blog",
    publisher: "Snyk",
    type: "rss",
    url: "https://snyk.io/blog/feed/",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "JFrog Security Research",
    publisher: "JFrog",
    type: "rss",
    url: "https://jfrog.com/blog/category/security/feed/",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Exploit-DB",
    publisher: "Exploit Database (OffSec)",
    type: "rss",
    url: "https://www.exploit-db.com/rss.xml",
    source_type: "exploit_disclosure",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Zero Day Initiative",
    publisher: "Zero Day Initiative (Trend Micro)",
    type: "rss",
    url: "https://www.zerodayinitiative.com/rss/published/",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Tenable Research",
    publisher: "Tenable",
    type: "rss",
    url: "https://www.tenable.com/blog/feed",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Qualys ThreatProtect",
    publisher: "Qualys",
    type: "rss",
    url: "https://blog.qualys.com/feed",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "rss",
  },

  // ── Incident response ──────────────────────────────────────────────────────

  {
    name: "The DFIR Report",
    publisher: "The DFIR Report",
    type: "rss",
    url: "https://thedfirreport.com/feed/",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Red Canary Blog",
    publisher: "Red Canary",
    type: "rss",
    url: "https://redcanary.com/blog/feed/",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "Huntress Blog",
    publisher: "Huntress",
    type: "rss",
    url: "https://www.huntress.com/blog/rss.xml",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },

  // ── Policy, strategy and standards ──────────────────────────────────────────

  {
    name: "OWASP",
    publisher: "OWASP",
    type: "atom",
    url: "https://owasp.org/feed.xml",
    source_type: "defensive_capability",
    trust_tier: "high",
    retrieval_method: "official_atom",
  },
  {
    name: "Georgetown CSET",
    publisher: "Georgetown CSET",
    type: "rss",
    url: "https://cset.georgetown.edu/feed/",
    source_type: "governance_signal",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "MITRE ATT&CK Blog",
    publisher: "MITRE ATT&CK",
    type: "rss",
    url: "https://medium.com/feed/mitre-attack",
    source_type: "adversary_adoption_signal",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },

  // ── Cloud and infrastructure security ────────────────────────────────────────

  {
    name: "AWS Security Blog",
    publisher: "Amazon Web Services",
    type: "rss",
    url: "https://aws.amazon.com/blogs/security/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },
  {
    name: "AWS Machine Learning Blog",
    publisher: "Amazon Web Services",
    type: "rss",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
  },

  // ── AI-enabled threats: deepfakes, disinformation, AI fraud ─────────────────

  {
    name: "DFRLab (Atlantic Council)",
    publisher: "Atlantic Council DFRLab",
    type: "rss",
    url: "https://dfrlab.org/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
  },

  // ── Security journalism ────────────────────────────────────────────────────

  {
    name: "Krebs on Security",
    publisher: "Krebs on Security",
    type: "rss",
    url: "https://krebsonsecurity.com/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
  },
  {
    name: "Schneier on Security",
    publisher: "Bruce Schneier",
    type: "atom",
    url: "https://www.schneier.com/feed/atom/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
  },
  {
    name: "The Record",
    publisher: "The Record",
    type: "rss",
    url: "https://therecord.media/feed/",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "404 Media",
    publisher: "404 Media",
    type: "rss",
    url: "https://www.404media.co/rss/",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "BleepingComputer",
    publisher: "BleepingComputer",
    type: "rss",
    url: "https://news.google.com/rss/search?q=site:bleepingcomputer.com&hl=en-US&gl=US&ceid=US:en",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    // Direct feed (bleepingcomputer.com/feed/) returns 403 from datacenter IPs (Cloudflare).
    // Google News RSS proxies BC articles cleanly; connector strips <source> tag to recover
    // the real bleepingcomputer.com URL. Returns ~100 recent items.
  },
  {
    name: "The Hacker News",
    publisher: "The Hacker News",
    type: "rss",
    url: "https://feeds.feedburner.com/TheHackersNews?format=xml",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "Dark Reading",
    publisher: "Dark Reading",
    type: "rss",
    url: "https://www.darkreading.com/rss.xml",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "SecurityWeek",
    publisher: "SecurityWeek",
    type: "rss",
    url: "https://feeds.feedburner.com/Securityweek",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "The Register Security",
    publisher: "The Register",
    type: "rss",
    url: "https://www.theregister.com/security/headlines.atom",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: false,  // feed URL returns non-feed / dead (confirmed Jul 2026)
  },
  {
    name: "Ars Technica Security",
    publisher: "Ars Technica",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "Wired Security",
    publisher: "Wired",
    type: "rss",
    url: "https://www.wired.com/feed/category/security/latest/rss",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "CyberScoop",
    publisher: "CyberScoop",
    type: "rss",
    url: "https://cyberscoop.com/feed/",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "Security Affairs",
    publisher: "Security Affairs",
    type: "rss",
    url: "https://securityaffairs.com/feed",
    source_type: "incident",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "Infosecurity Magazine",
    publisher: "Infosecurity Magazine",
    type: "rss",
    url: "https://www.infosecurity-magazine.com/rss/news/",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "Cybersecurity Dive",
    publisher: "Cybersecurity Dive",
    type: "rss",
    url: "https://www.cybersecuritydive.com/feeds/news/",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
  {
    name: "Help Net Security",
    publisher: "Help Net Security",
    type: "rss",
    url: "https://www.helpnetsecurity.com/feed/",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
  },
];
