/**
 * Source registry — connector definitions for ingestion.
 *
 * source_type values MUST be from the controlled vocabulary in
 * lib/config/sourceTypes.js. Layer 5 (validateAndTypeSource) will
 * re-classify any source whose source_type doesn't match, but setting
 * the right value here avoids redundant work.
 *
 * Acceptable source_type values:
 *   vulnerability, incident, exploit_disclosure, threat_intelligence,
 *   adversary_adoption_signal, research_finding, benchmark_evaluation,
 *   capability_demonstration, defensive_capability, governance_signal,
 *   societal_harm_signal, attack_surface_signal, unknown
 */

export const SOURCE_REGISTRY = [
  {
    name: "CISA Advisories",
    publisher: "CISA",
    type: "rss",
    url: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Microsoft Security Blog",
    publisher: "Microsoft",
    type: "rss",
    url: "https://www.microsoft.com/en-us/security/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Cloud Threat Intelligence",
    publisher: "Google Cloud / Mandiant",
    type: "rss",
    url: "https://cloud.google.com/blog/topics/threat-intelligence/rss/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Google Security Blog",
    publisher: "Google",
    type: "atom",
    url: "https://security.googleblog.com/feeds/posts/default",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "OWASP",
    publisher: "OWASP",
    type: "rss",
    url: "https://owasp.org/feed.xml",
    source_type: "defensive_capability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "NIST AI",
    publisher: "NIST",
    type: "html_reference",
    url: "https://www.nist.gov/artificial-intelligence",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_site",
    enabled: false,
  },
  {
    name: "OECD AI",
    publisher: "OECD AI Policy Observatory",
    type: "html_reference",
    url: "https://oecd.ai/",
    source_type: "governance_signal",
    trust_tier: "high",
    retrieval_method: "official_site",
    enabled: false,
  },
  {
    name: "The Hacker News",
    publisher: "The Hacker News",
    type: "rss",
    url: "https://feeds.feedburner.com/TheHackersNews?format=xml",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Dark Reading",
    publisher: "Dark Reading",
    type: "rss",
    url: "https://www.darkreading.com/rss.xml",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Krebs on Security",
    publisher: "Krebs on Security",
    type: "rss",
    url: "https://krebsonsecurity.com/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "SANS Internet Storm Center",
    publisher: "SANS ISC",
    type: "rss",
    url: "https://isc.sans.edu/rssfeed_full.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── AI incident tracking ──────────────────────────────────────────────────────

  {
    name: "AI Incident Database",
    publisher: "AI Incident Database",
    type: "rss",
    url: "https://incidentdatabase.ai/rss.xml",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,  // re-enabled: AI relevance gate + v2 pre-screen handle off-topic noise
  },
  {
    name: "AVID AI Vulnerability Blog",
    publisher: "AVID (AI Vulnerability Database)",
    type: "rss",
    url: "https://avidml.org/blog/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "ML Safety Newsletter",
    publisher: "Center for AI Safety",
    type: "rss",
    url: "https://newsletter.mlsafety.org/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── Horizon scanning: AI policy, strategy and foresight ──────────────────────

  {
    name: "Georgetown CSET",
    publisher: "Georgetown CSET",
    type: "rss",
    url: "https://cset.georgetown.edu/feed/",
    source_type: "governance_signal",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "MIT Technology Review AI",
    publisher: "MIT Technology Review",
    type: "rss",
    url: "https://www.technologyreview.com/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: false, // broad tech journalism, rarely security-specific — removed per quality review
  },
  {
    name: "The Register Security",
    publisher: "The Register",
    type: "atom",
    url: "https://www.theregister.com/security/headlines.atom",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "official_atom",
    enabled: true,
  },

  // ── Adversarial ML & AI red teaming ──────────────────────────────────────────

  {
    name: "Adversa AI Research",
    publisher: "Adversa AI",
    type: "rss",
    url: "https://adversa.ai/blog/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "HiddenLayer Research",
    publisher: "HiddenLayer",
    type: "rss",
    url: "https://hiddenlayer.com/research/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: false, // feed removed — no working RSS URL found
  },
  {
    name: "Protect AI Blog",
    publisher: "Protect AI",
    type: "rss",
    url: "https://protectai.com/blog/rss.xml",
    source_type: "vendor_report",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: false, // vendor marketing blog — removed per quality review
  },
  {
    name: "Lakera AI Blog",
    publisher: "Lakera AI",
    type: "rss",
    url: "https://www.lakera.ai/blog/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: false, // acquired by Cisco 2024 — no working RSS URL found
  },
  {
    name: "Cisco Security Advisories",
    publisher: "Cisco",
    type: "rss",
    url: "https://sec.cloudapps.cisco.com/security/center/rss.x",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Bishop Fox Blog",
    publisher: "Bishop Fox",
    type: "rss",
    url: "https://bishopfox.com/blog/feed",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── AI-specific security research and incident feeds ─────────────────────────

  {
    name: "Embrace The Red",
    publisher: "Wunderwuzzi (Embrace The Red)",
    type: "rss",
    url: "https://embracethered.com/blog/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Simon Willison's Weblog",
    publisher: "Simon Willison",
    type: "atom",
    url: "https://simonwillison.net/atom/everything/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,  // re-enabled: documents real-world prompt injection / LLM exploits;
    // AI relevance gate filters non-security posts; v2 pre-screen handles remaining noise
  },
  {
    name: "Trail of Bits Blog",
    publisher: "Trail of Bits",
    type: "rss",
    url: "https://blog.trailofbits.com/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Elastic Security Labs",
    publisher: "Elastic",
    type: "rss",
    url: "https://www.elastic.co/security-labs/rss/feed.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Anthropic News",
    publisher: "Anthropic",
    type: "atom",
    url: "https://www.anthropic.com/rss.xml",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_atom",
    enabled: false, // Anthropic does not publish an RSS/Atom feed
  },
  {
    name: "OpenAI Blog",
    publisher: "OpenAI",
    type: "rss",
    url: "https://openai.com/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "NIST AI",
    publisher: "NIST",
    type: "rss",
    url: "https://www.nist.gov/blogs/cybersecurity-insights/rss.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── AI-focused threat intelligence ───────────────────────────────────────────

  {
    name: "Unit 42 Threat Research",
    publisher: "Palo Alto Networks Unit 42",
    type: "rss",
    url: "https://unit42.paloaltonetworks.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "CrowdStrike Blog",
    publisher: "CrowdStrike",
    type: "rss",
    url: "https://www.crowdstrike.com/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Recorded Future Blog",
    publisher: "Recorded Future",
    type: "rss",
    url: "https://www.recordedfuture.com/feed",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "IBM Security Intelligence",
    publisher: "IBM Security",
    type: "rss",
    url: "https://securityintelligence.com/feed/",
    source_type: "vendor_report",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: false, // IBM product marketing dominates — removed per quality review
  },
  {
    name: "Schneier on Security",
    publisher: "Bruce Schneier",
    type: "atom",
    url: "https://www.schneier.com/feed/atom/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },

  // ── Government and regulatory (AI/cyber policy) ───────────────────────────────

  {
    name: "NCSC UK",
    publisher: "UK National Cyber Security Centre",
    type: "atom",
    url: "https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "CSA Singapore",
    publisher: "Cyber Security Agency of Singapore",
    type: "rss",
    url: "https://www.csa.gov.sg/rss",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: false, // returns 403 — blocks non-browser requests
  },
  {
    name: "ENISA News",
    publisher: "European Union Agency for Cybersecurity",
    type: "rss",
    url: "https://www.enisa.europa.eu/news/rss",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: false, // feed URL no longer exists (404)
  },

  // ── Broad security news (high volume, AI content filtered at classify time) ───

  {
    name: "BleepingComputer",
    publisher: "BleepingComputer",
    type: "rss",
    url: "https://www.bleepingcomputer.com/feed/",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "SecurityWeek",
    publisher: "SecurityWeek",
    type: "rss",
    url: "https://feeds.feedburner.com/Securityweek",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Help Net Security",
    publisher: "Help Net Security",
    type: "rss",
    url: "https://www.helpnetsecurity.com/feed/",
    source_type: "news_article",
    trust_tier: "low",
    retrieval_method: "rss",
    enabled: false, // press release aggregator — removed per quality review
  },
  {
    name: "Ars Technica Security",
    publisher: "Ars Technica",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Wired Security",
    publisher: "Wired",
    type: "rss",
    url: "https://www.wired.com/feed/category/security/latest/rss",
    source_type: "news_article",
    trust_tier: "medium",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── AI-enabled threats: deepfakes, disinformation, AI fraud ─────────────────

  {
    name:        "DFRLab (Atlantic Council)",
    publisher:   "Atlantic Council DFRLab",
    type:        "rss",
    url:         "https://dfrlab.org/feed/",
    source_type: "threat_intelligence",
    trust_tier:  "high",
    retrieval_method: "rss",
    enabled:     true,
  },
  {
    name:        "404 Media",
    publisher:   "404 Media",
    type:        "rss",
    url:         "https://www.404media.co/rss/",
    source_type: "news_article",
    trust_tier:  "medium",
    retrieval_method: "rss",
    enabled:     true,
  },
  {
    name:        "The Record",
    publisher:   "The Record",
    type:        "rss",
    url:         "https://therecord.media/feed/",
    source_type: "news_article",
    trust_tier:  "medium",
    retrieval_method: "rss",
    enabled:     true,
  },

  // ── Threat intel: incidents, AI malware, social engineering ───────────────

  {
    name: "Talos Intelligence Blog",
    publisher: "Cisco Talos",
    type: "rss",
    url: "https://blog.talosintelligence.com/rss/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "SentinelLabs Research",
    publisher: "SentinelOne",
    type: "rss",
    url: "https://www.sentinelone.com/labs/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Sophos X-Ops",
    publisher: "Sophos",
    type: "rss",
    url: "https://news.sophos.com/en-us/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Proofpoint Threat Research",
    publisher: "Proofpoint",
    type: "rss",
    url: "https://www.proofpoint.com/us/blog/threat-insight/rss",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Mandiant Threat Intelligence",
    publisher: "Mandiant",
    type: "rss",
    url: "https://www.mandiant.com/resources/blog/rss.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── AI supply chain & package vulnerabilities ─────────────────────────────────

  {
    name: "Snyk Security Blog",
    publisher: "Snyk",
    type: "rss",
    url: "https://snyk.io/blog/feed/",
    source_type: "vulnerability_advisory",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Socket Security Blog",
    publisher: "Socket",
    type: "rss",
    url: "https://socket.dev/blog/rss.xml",
    source_type: "vulnerability_advisory",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "JFrog Security Research",
    publisher: "JFrog",
    type: "rss",
    url: "https://jfrog.com/blog/category/security/feed/",
    source_type: "vulnerability_advisory",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },

  // ── AWS / cloud AI security ───────────────────────────────────────────────────

  {
    name: "AWS Security Blog",
    publisher: "Amazon Web Services",
    type: "rss",
    url: "https://aws.amazon.com/blogs/security/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "AWS Machine Learning Blog",
    publisher: "Amazon Web Services",
    type: "rss",
    url: "https://aws.amazon.com/blogs/machine-learning/feed/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── Anthropic / AI lab research ───────────────────────────────────────────────

  {
    name: "Transformer Circuits (Anthropic Interpretability)",
    publisher: "Anthropic",
    type: "rss",
    url: "https://transformer-circuits.pub/feed.xml",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "DeepMind Safety Research",
    publisher: "Google DeepMind",
    type: "rss",
    url: "https://deepmind.google/blog/feed/rss/",
    source_type: "research_finding",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── Operational / incident-response feeds (added to lift under-represented
  //    incident + threat-intelligence genres; see docs/CORPUS_COMPOSITION_AUDIT.md).
  //    All URLs validated live (rss/xml) on 2026-06-24. ───────────────────────
  {
    name: "The DFIR Report",
    publisher: "The DFIR Report",
    type: "rss",
    url: "https://thedfirreport.com/feed/",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Red Canary Blog",
    publisher: "Red Canary",
    type: "rss",
    url: "https://redcanary.com/blog/feed/",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Huntress Blog",
    publisher: "Huntress",
    type: "rss",
    url: "https://www.huntress.com/blog/rss.xml",
    source_type: "incident",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Check Point Research",
    publisher: "Check Point Research",
    type: "rss",
    url: "https://research.checkpoint.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Securelist (Kaspersky)",
    publisher: "Kaspersky",
    type: "rss",
    url: "https://securelist.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "ESET WeLiveSecurity",
    publisher: "ESET",
    type: "rss",
    url: "https://www.welivesecurity.com/en/rss/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── Additional operational feeds (added 2026-06-24 to address research dominance) ──

  {
    name: "Google TAG (Threat Analysis Group)",
    publisher: "Google TAG",
    type: "atom",
    url: "https://blog.google/threat-analysis-group/rss/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: true,
  },
  {
    name: "Volexity Threat Research",
    publisher: "Volexity",
    type: "rss",
    url: "https://www.volexity.com/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "WithSecure Research",
    publisher: "WithSecure",
    type: "rss",
    url: "https://labs.withsecure.com/rss.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "NSA Cybersecurity Advisories",
    publisher: "NSA",
    type: "rss",
    url: "https://www.nsa.gov/news-features/cybersecurity-advisories/rss/",
    source_type: "governance_signal",
    trust_tier: "primary",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Lumen Black Lotus Labs",
    publisher: "Lumen Black Lotus Labs",
    type: "rss",
    url: "https://blog.lumen.com/category/black-lotus-labs/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Microsoft MSTIC",
    publisher: "Microsoft Threat Intelligence",
    type: "rss",
    url: "https://www.microsoft.com/en-us/security/blog/topic/threat-intelligence/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "MITRE ATT&CK Blog",
    publisher: "MITRE ATT&CK",
    type: "rss",
    url: "https://medium.com/feed/mitre-attack",
    source_type: "adversary_adoption_signal",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Abnormal Security Blog",
    publisher: "Abnormal Security",
    type: "rss",
    url: "https://abnormalsecurity.com/blog/rss.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "SlashNext AI Threat Intelligence",
    publisher: "SlashNext",
    type: "rss",
    url: "https://slashnext.com/blog/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── Lane E: Agentic AI ecosystem security monitoring (added 2026-06-24) ────────
  // These feeds track security disclosures, vulnerabilities, and incidents in the
  // agentic AI framework ecosystem — LangChain, CrewAI, AutoGen, MCP servers, etc.
  // Source type: attack_surface_signal — these are not yet incidents but track the
  // expanding attack surface of AI agent infrastructure.

  {
    name: "LangChain Blog",
    publisher: "LangChain",
    type: "rss",
    url: "https://blog.langchain.dev/rss/",
    source_type: "attack_surface_signal",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Simon Willison's Weblog (LLM security)",
    publisher: "Simon Willison",
    type: "atom",
    url: "https://simonwillison.net/atom/entries/",
    // already in registry as "Simon Willison's Weblog" — this is the entries-only feed
    // which has better date metadata than everything/ feed
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: false,  // duplicate of the existing Simon Willison entry
  },
  {
    name: "Wiz Research Blog",
    publisher: "Wiz",
    type: "rss",
    url: "https://www.wiz.io/blog/rss.xml",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "NCC Group Research",
    publisher: "NCC Group",
    type: "rss",
    url: "https://research.nccgroup.com/feed/",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Palisade Research",
    publisher: "Palisade Research",
    type: "rss",
    url: "https://palisaderesearch.org/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "HiddenLayer Research Blog",
    publisher: "HiddenLayer",
    type: "rss",
    url: "https://hiddenlayer.com/research/rss/",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Protect AI Blog",
    publisher: "Protect AI",
    type: "rss",
    url: "https://protectai.com/blog/rss.xml",
    source_type: "vulnerability",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Lakera AI Blog",
    publisher: "Lakera",
    type: "rss",
    url: "https://www.lakera.ai/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── Lane D additions: more TI vendor coverage ─────────────────────────────────
  {
    name: "Trend Micro Research",
    publisher: "Trend Micro",
    type: "rss",
    url: "https://feeds.trendmicro.com/Anti-MalwareBlog",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Palo Alto Networks Unit 42 (ATOM)",
    publisher: "Unit 42",
    type: "atom",
    url: "https://unit42.paloaltonetworks.com/feed/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_atom",
    enabled: false,  // duplicate of Unit 42 entry already above; keep disabled
  },
  {
    name: "Zscaler ThreatLabz",
    publisher: "Zscaler ThreatLabz",
    type: "rss",
    url: "https://www.zscaler.com/blogs/security-research/rss.xml",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },
  {
    name: "Rapid7 Threat Intelligence",
    publisher: "Rapid7",
    type: "rss",
    url: "https://www.rapid7.com/blog/tag/threat-intelligence/rss/",
    source_type: "threat_intelligence",
    trust_tier: "high",
    retrieval_method: "official_rss",
    enabled: true,
  },

  // ── Tier A: AI-native independent / red-team blogs (added 2026-06-25) ──────────
  // The Embrace-the-Red archetype: blogs that are ~100% AI-security content (prompt
  // injection, jailbreaks, agent/LLM exploitation). Selected over general "hacker"
  // blogs because a keyword probe showed general offensive feeds (watchTowr,
  // Assetnote, PortSwigger, Project Zero) are <13% AI-specific and fail the
  // AI-relevance gate. See docs/OPERATIONAL_SOURCE_EXPANSION_PLAN.md.
  {
    name: "Joseph Thacker (rez0)",
    publisher: "Joseph Thacker",
    type: "rss",
    url: "https://josephthacker.com/feed.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Kai Greshake",
    publisher: "Kai Greshake",
    type: "rss",
    url: "https://kai-greshake.de/index.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Knostic Blog",
    publisher: "Knostic",
    type: "rss",
    url: "https://www.knostic.ai/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
  {
    name: "Promptfoo Blog",
    publisher: "Promptfoo",
    type: "rss",
    url: "https://www.promptfoo.dev/blog/rss.xml",
    source_type: "research_finding",
    trust_tier: "high",
    retrieval_method: "rss",
    enabled: true,
  },
];
