/**
 * L8 — Script Generation QA
 *
 * Two-pass QA for generated presenter scripts:
 *   Pass 1 (always): deterministic structural and content checks
 *   Pass 2 (optional): second-model LLM validation
 *     - if script generated by Anthropic → validate with Gemini
 *     - if script generated by Gemini → validate with Anthropic (if key available)
 *     - otherwise deterministic only
 *
 * Checks:
 *   - Script is 6–10 sentences for content slides
 *   - Script does not merely restate slide bullets
 *   - Script has a transition or "so what" sentence
 *   - No invented statistics (numbers in script not present in slide)
 *   - No exaggerated language
 *   - Sentences are not too long (hard to say aloud)
 *   - Script is not empty or too short
 */

import { routedLLM } from "../../llm/llmRouter.js";

// Slide types that require full scripts (6-10 sentences)
const FULL_SCRIPT_TYPES = new Set([
  "exec_overview", "changes_year", "biggest_developments", "landscape",
  "category_insights", "category_content", "cross_category", "cross_category_analysis",
  "outlook", "recommendations", "conclusion",
]);

// Slide types that only need brief script (1-4 sentences)
const BRIEF_SCRIPT_TYPES = new Set([
  "section_divider", "title", "appendix", "references",
]);

// Words that signal over-dramatisation
const HYPERBOLE_WORDS = /\b(unprecedented|shocking|alarming|explosive|devastating|staggering|catastrophic|revolutionary|game-changing|paradigm-shifting)\b/i;

// Transition markers — at least one should appear
const TRANSITION_MARKERS = /\b(next|let.{1,15}turn|moving to|on the next|that brings|let.{1,15}look|now|the following)\b/i;

// Phrases that require analytics evidence to be credible — checked in scripts
const UNSUPPORTED_TREND_WORDS = /\b(tripling|doubling|fastest\s+grow|rapid(?:ly)?\s+grow|rapid\s+growth|dominate[sd]?|outpac(?:e[sd]?|ing)|surg(?:e[sd]?|ing))\b/i;

// Phrases that fabricate urgency or certainty without evidence
const FABRICATED_CERTAINTY = /\b(the evidence (?:confirms?|proves?|demonstrates?|shows?) that|is (?:now|already) (?:confirmed|proven|established)|definitively shows?)\b/i;

// Fabricated evidence framing — "the evidence suggests" when no evidence exists
const FAKE_EVIDENCE_FRAME = /\b(the evidence (?:suggests?|indicates?|points? to))\b/i;

// ── Deterministic checks ──────────────────────────────────────────────────────

function countSentences(text) {
  if (!text || text.trim().length === 0) return 0;
  // Split on .!? followed by space or end-of-string
  const matches = text.match(/[.!?]+(?:\s|$)/g) || [];
  return Math.max(matches.length, 1);
}

function extractNumbersFromText(text) {
  return (text || "").match(/\b\d[\d,.%]*\b/g) || [];
}

function bulletText(b) {
  if (!b) return "";
  return typeof b === "object" ? (b.text || "") : String(b);
}

function bulletOverlap(scriptText, bullets) {
  if (!bullets || bullets.length === 0) return false;
  const scriptLower = scriptText.toLowerCase();
  let overlapping = 0;
  for (const bullet of bullets) {
    const bulletWords = bulletText(bullet).toLowerCase().split(/\s+/).filter((w) => w.length > 4);
    // If 4+ meaningful words of the bullet appear verbatim in the script
    const phrase = bulletWords.slice(0, 5).join(" ");
    if (phrase.length > 20 && scriptLower.includes(phrase)) overlapping++;
  }
  return overlapping >= Math.ceil(bullets.length * 0.6);
}

function runDeterministicQa(slide, scriptText) {
  const issues = [];
  const slideType = slide.slide_type || "unknown";

  if (!scriptText || scriptText.trim().length < 20) {
    return {
      qa_pass: false,
      issues: ["script_empty_or_too_short"],
      second_model_used: false,
    };
  }

  const sentenceCount = countSentences(scriptText);

  if (FULL_SCRIPT_TYPES.has(slideType)) {
    if (sentenceCount < 5) issues.push(`script_too_short (${sentenceCount} sentences, need 6+)`);
    if (sentenceCount > 12) issues.push(`script_too_long (${sentenceCount} sentences, max 10)`);
  } else if (BRIEF_SCRIPT_TYPES.has(slideType)) {
    if (sentenceCount > 5) issues.push(`script_too_long_for_type (${sentenceCount} sentences, max 4 for ${slideType})`);
  }

  // Check for bullet repetition
  if (bulletOverlap(scriptText, slide.bullets)) {
    issues.push("script_largely_restates_bullets");
  }

  // Check for transition (content slides only)
  if (FULL_SCRIPT_TYPES.has(slideType) && !TRANSITION_MARKERS.test(scriptText)) {
    issues.push("no_transition_or_so_what_detected");
  }

  // Check for hyperbole
  const hyperboleMatch = scriptText.match(HYPERBOLE_WORDS);
  if (hyperboleMatch) {
    issues.push(`exaggerated_language_detected: "${hyperboleMatch[0]}"`);
  }

  // Check for unsupported trend/growth language — only allowed when analytics backs it
  const trendMatch = scriptText.match(UNSUPPORTED_TREND_WORDS);
  if (trendMatch) {
    const analyticsHasTrend = (slide.analytics_evidence || []).some((e) =>
      (e.top_entries || []).some((entry) => entry.key !== "unknown" && (entry.count || 0) > 0)
    );
    if (!analyticsHasTrend) {
      issues.push(`unsupported_trend_claim: "${trendMatch[0]}" — no analytics evidence with non-unknown data to support this`);
    }
  }

  // Check for fabricated certainty framing
  const certaintyMatch = scriptText.match(FABRICATED_CERTAINTY);
  if (certaintyMatch) {
    issues.push(`fabricated_certainty: "${certaintyMatch[0].slice(0, 60)}" — avoid absolute certainty claims without direct evidence citation`);
  }

  // Check for fake evidence framing when slide has no evidence
  const hasNoEvidence = (slide.evidence_callouts || []).length === 0 &&
    (slide._plan?.rawfact_evidence_ids?.length || 0) === 0;
  if (hasNoEvidence && FAKE_EVIDENCE_FRAME.test(scriptText)) {
    issues.push(`fake_evidence_frame: script uses "the evidence suggests/indicates" but slide has no evidence callouts or rawfact IDs — this is a fabricated evidentiary claim`);
  }

  // Check for invented numbers (numbers in script not in slide content or evidence)
  const slideNumbers = new Set(
    extractNumbersFromText([
      slide.headline,
      ...(slide.bullets || []),
      ...(slide.evidence_callouts || []).map((c) => `${c.key_fact || ""} ${c.publisher || ""}`),
      ...(slide.citations || []),
    ].join(" "))
  );
  const scriptNumbers = extractNumbersFromText(scriptText);
  const inventedNumbers = scriptNumbers.filter((n) => !slideNumbers.has(n) && n.length > 1 && !/^[1-9]$/.test(n));
  if (inventedNumbers.length > 0) {
    issues.push(`hallucinated_statistic_in_script: numbers not in slide content: ${inventedNumbers.slice(0, 3).join(", ")}`);
  }

  // Check for overly long sentences (hard to say aloud)
  const sentences = scriptText.split(/[.!?]+\s+/);
  const longSentences = sentences.filter((s) => s.split(/\s+/).length > 30);
  if (longSentences.length > 0) {
    issues.push(`${longSentences.length} sentence(s) over 30 words (hard to say aloud)`);
  }

  return {
    qa_pass: issues.length === 0,
    issues,
    second_model_used: false,
  };
}

// ── Second-model LLM QA ───────────────────────────────────────────────────────

const LLM_QA_SCHEMA = {
  type: "object",
  required: ["qa_pass", "issues"],
  properties: {
    qa_pass:         { type: "boolean" },
    issues:          { type: "array", items: { type: "string" } },
    tone_assessment: { type: "string", enum: ["professional", "too_casual", "too_dramatic", "too_dry"] },
    has_transition:  { type: "boolean" },
  },
};

const SECOND_MODEL_SYSTEM = `You are a QA reviewer for presenter scripts in an AI threat intelligence briefing.

Evaluate the script against the slide content. Return strict JSON.

Check:
1. Does the script introduce any claim or statistic NOT present in the slide content?
2. Is the tone professional and objective (not dramatic, not casual, not marketing)?
3. Does the script avoid simply restating bullets?
4. Does the script include a transition or implication?

Return: { qa_pass: true/false, issues: [...strings], tone_assessment: "professional|too_casual|too_dramatic|too_dry", has_transition: true/false }`;

function buildSecondModelPrompt(slide, scriptText) {
  return [
    `SLIDE: ${slide.slide_number} — ${slide.title}`,
    `HEADLINE: ${slide.headline || "(none)"}`,
    `BULLETS:\n${(slide.bullets || []).map((b) => `- ${bulletText(b)}`).join("\n") || "(none)"}`,
    `EVIDENCE:\n${(slide.evidence_callouts || []).map((c) => `• ${c.publisher}: ${c.key_fact}`).join("\n") || "(none)"}`,
    ``,
    `GENERATED SCRIPT:`,
    scriptText,
    ``,
    `Evaluate the script. Return JSON with qa_pass, issues[], tone_assessment, has_transition.`,
  ].join("\n");
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Run QA on a generated presenter script.
 *
 * @param {object}  slide       - Finalized slide with content fields
 * @param {string}  scriptText  - Generated script text
 * @param {object}  [opts]
 * @param {boolean} [opts.skipSecondModel=true]
 * @param {string}  [opts.primaryProvider]  - Provider that generated the script
 * @returns {Promise<object>}
 */
export async function qaScript(slide, scriptText, opts = {}) {
  const { skipSecondModel = true, primaryProvider = "unknown" } = opts;

  // Pass 1: deterministic
  const det = runDeterministicQa(slide, scriptText);

  // Pass 2 is reserved for slides the deterministic pass actually flagged — a
  // clean deterministic result does not need a second-model LLM call. This cuts
  // script-QA LLM calls from "every slide" to "only the few with issues".
  if (skipSecondModel || BRIEF_SCRIPT_TYPES.has(slide.slide_type) || det.issues.length === 0) {
    return det;
  }

  // Pass 2: second-model validation
  // Use a different provider from the one that generated the script
  // Anthropic-generated → validate with Gemini (final_qa task)
  // Gemini-generated → validate with Anthropic (if key available)
  try {
    const { result } = await routedLLM(
      SECOND_MODEL_SYSTEM,
      buildSecondModelPrompt(slide, scriptText),
      {
        task:          "final_qa",
        requires_json: true,
        schema:        LLM_QA_SCHEMA,
        logLabel:      `L8-script-qa-${slide.slide_number}`,
      }
    );

    if (!result) return det;

    const allIssues = [...det.issues, ...(result.issues || [])];
    const qa_pass = det.qa_pass && result.qa_pass !== false;

    return {
      qa_pass,
      issues:          allIssues,
      tone_assessment: result.tone_assessment || "professional",
      has_transition:  result.has_transition ?? true,
      second_model_used: true,
    };
  } catch (err) {
    process.stdout.write(`  [L8-script-qa] Second model failed for slide ${slide.slide_number}: ${err.message}\n`);
    return det;
  }
}

/**
 * Run script QA for all slides in the deck.
 *
 * @param {object[]} slides
 * @param {object}   [opts]
 * @param {boolean}  [opts.skipSecondModel=true]
 * @returns {Promise<object[]>} Slides with `script_qa` field added
 */
export async function qaAllScripts(slides, opts = {}) {
  const results = [];
  // Global cap on second-model script-QA calls per run (env-tunable).
  let secondModelBudget = Number(process.env.SCRIPT_QA_MAX_LLM) || 12;

  for (const slide of slides) {
    // Only allow a second-model pass while budget remains; otherwise force
    // deterministic-only for this slide.
    const slideOpts = secondModelBudget > 0 ? opts : { ...opts, skipSecondModel: true };
    const qa = await qaScript(slide, slide.speaker_notes || "", slideOpts);
    if (qa.second_model_used) secondModelBudget--;
    results.push({ ...slide, script_qa: qa });
  }

  const issues = results.filter((s) => s.script_qa?.issues?.length > 0);
  if (issues.length > 0) {
    process.stdout.write(
      `  [L8-script-qa] ${issues.length}/${slides.length} scripts have QA issues\n`
    );
  }

  return results;
}
